[workspace]
members = [
    "brain",
    "brain-test-data",
    "collect",
    "common",
    "dom",
    "oven",
    "play",
    "simulate",
]

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io]
#rlbot = { path = "../rlbot-rust" }
#chip = { path = "../chip" }
