[package]
name = "simulate"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"

nalgebra = "0.16.0"
ncollide3d = "0.17.1"

rlbot = "0.2.0"

common = { path = "../common" }
oven = { path = "../oven" }

[features]
strict = []
