[package]
name = "collect"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
csv = "1.0.2"
flatbuffers = "0.5.0"
ordered-float = "1.0.1"

nalgebra = "0.18.0"

rlbot = "0.4.1"

common = { path = "../common" }

[features]
strict = []
