[package]
name = "common"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
flatbuffers = "0.5.0"
lazy_static = "1.1.0"
smallvec = "0.6.9"

nalgebra = "0.16.0"

rlbot = "0.4.0"

[dev-dependencies]
chip = "0.0.5"

[features]
strict = []
