[package]
name = "dom"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.0"

rlbot = "0.2.0"

common = { path = "../common" }

[dev-dependencies]
chip = "0.0.5"

[features]
strict = []
